### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/pcp#3]
* three files to download
* preview / verify functionality and UI? how might this be different than or redundant to current "Review" step? informed by #27 
* "Save as Draft"?

**Comment by francisrupert** [comment]
* `pro171020.txt`
* `ldprates.txt`
* `mkt171020.txt`

![image](https://user-images.githubusercontent.com/1165933/31775650-d844aca8-b4ae-11e7-9cb1-75d1b8e1fb17.png)

**Comment by francisrupert** [comment]
Initial stab:

![image](https://user-images.githubusercontent.com/1165933/32294099-32f12b40-bf13-11e7-96d7-ebec409ab91f.png)

**Comment by francisrupert** [comment]
- [ ] Add file size
- [ ] Add file name
- [ ] "Download" button vs text link?
- [ ] Checkbox as last column (fix the "linear" order somehow)

**Comment by francisrupert** [comment]
@arosenblum, @atdiff,

How does **[this screencast](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/screencasts/pcp-publish.webm)** look for **Publish**, as discussed yesterday? Screenshot below too:

![image](https://user-images.githubusercontent.com/1165933/32631058-a051578a-c564-11e7-91c2-31ab32341eee.png)

**Comment by francisrupert** [comment]
@atdiff and @arosenblum,

Please review the **[screencast demo'ing recent changes to Closing, and through Publish](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/screencasts/close-through-publish.webm)**. I'd like your reactions before I share with Michelle and Kathleen.

And it's viewable at the **[UX Prototype's /dev/ URL](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/dev/workflow_discovery.html)**.

(ref: #27, #8, #3)

**Comment by atdiff** [comment]
@francisrupert looks great!  Only question is whether the save button on closing page should be enabled if they haven't entered any text in the text box.  Will we allow them to save with no message?

**Comment by francisrupert** [comment]
closed via bcf790a

**Comment by francisrupert** [comment]
Follow-up actions based on feedback:

Language for confirmation prompt, something to effect of....

> By completing Publish, I have validated and verified all published documents for March 22, 2017. 
> This effective date will no longer be accessible for processing.

...and I probably should apply the two-factor, checkbox-enable-button pattern.

**Comment by francisrupert** [comment]
approved and closing
