### ISSUE TITLE
Empty State Adjustments panel

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/pcp#34]
"There are none, add one!"

**Comment by francisrupert** [comment]
@atdiff, @arosenblum,

How's this look for the "empty adjustment panel" on **[this screencast](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/screencasts/empty-adjustment-panel.webm)**? Preview image below:

![image](https://user-images.githubusercontent.com/1165933/32803019-c4544c50-c947-11e7-9a43-0d96313e0f81.png)

**Comment by atdiff** [comment]
@francisrupert looks great!
