### ISSUE TITLE
5/30 calculation

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/pcp#43]
### Ask

Prototype a UI mechanism to display 5- and 30-day calculations. Is it a button or...?

### Implications

* When invoked, all adjustment functionality is disabled.
* What items/layers are _removed_?

### Background

https://issues.tools.fsa.usda.gov/browse/PCPII-877

To be prototyped in concert with #12 

### Initial dev stab

(via @atdiff)

![image](https://user-images.githubusercontent.com/1165933/32854736-3325759c-ca05-11e7-9e1e-545383ef1278.png)

**Comment by francisrupert** [comment]
Initial sketch:

![image](https://user-images.githubusercontent.com/1165933/32858092-ddd36300-ca0f-11e7-846b-beb407c0cfa6.png)

**Comment by francisrupert** [comment]
@atdiff,

Initial stab in below screenshot. Whatchathink? 

![image](https://user-images.githubusercontent.com/1165933/33041312-87fa43c0-ce03-11e7-95af-d92d310e62a0.png)

**Comment by atdiff** [comment]
@francisrupert Looks great!  Fits in really well with the overall flow of the app

**Comment by francisrupert** [comment]
@atdiff,

**[UX Prototype `/dev/` URL](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/dev/workflow_mapping.html)** updated with what I showed you this afternoon.

**Comment by atdiff** [comment]
Looks great!
