### ISSUE TITLE
Panel toggle SVG not displaying in IE

### ISSUE THREAD

**Issue by atdiff** [USDA-FSA/pcp#60]
After making the various related updates, the image for toggling the panel appears fine in Chrome but doesn't appear at all in IE.

Chrome:
![image](https://user-images.githubusercontent.com/16138266/33496823-4739c856-d691-11e7-9596-4e81a5111205.png)

IE:
![image](https://user-images.githubusercontent.com/16138266/33496847-58e408fa-d691-11e7-87df-03450433466f.png)

**Comment by francisrupert** [comment]
Good catch.

Forgot to mention IE doesn't play nice with Sprite-like, inline SVG sourcemaps. You'll need to add the polyfill https://github.com/USDA-FSA/pcp/blob/master/src/js/vendor/svgxuse.js

General info: https://github.com/jonathantneal/svg4everybody/blob/master/README.md

svgxuse.js is a fork of that, I believe (or at least replicates it in principle), included with the open source icons I sourced from icomoon.io. 

Also, Saturday...? 😛

**Comment by francisrupert** [comment]
Actually here's the README for svgxuse.js, if at all needed: https://github.com/Keyamoon/svgxuse/blob/master/readme.md

**Comment by atdiff** [comment]
Worked great. Thanks!
